### ISSUE TITLE
www.lifemiles.com - design is broken

### ISSUE THREAD

**Issue by miketaylr** [webcompat/pretriage-test-issues#28]
**URL**: https://www.lifemiles.com/esp/use/red/bookingengine.aspx

**Browser / Version**: Firefox 62.0
**Operating System**: Windows 7
**Tested Another Browser**: Unknown

**Problem type**: Design is broken
**Description**: site is not working
**Steps to Reproduce**:

[![Screenshot Description](https://webcompat.com/uploads/2018/5/15beef3a-818e-47d5-ace2-9186fc450adc-thumb.jpg)](https://webcompat.com/uploads/2018/5/15beef3a-818e-47d5-ace2-9186fc450adc.jpg)

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>buildID: 20180510100205</li><li>gfx.webrender.blob-images: true</li><li>gfx.webrender.all: false</li><li>gfx.webrender.enabled: false</li><li>image.mem.shared: true</li><li>channel: nightly</li>
</ul>
</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by hellosct1** [comment]
Testing in

* Linux (debian / ubuntu / mint)
Nightly 64.0a1 (2018-09-26)  with and without responsive
Firefox 62  with and without responsive
Chromium 65.0.3325.181

* windows 8
Nightly 64.0a1 (2018-09-26) 
Firefox 62  with and without responsive
Chrome Version 69.0.3497.100


* Android 6
Firefox Focus 7.0.5
Firefox 62
Nightly 64.0a1 (2018-09-26) 
Chrome


Under **Firefox Focus**, you can't access the website because of the captcha when all privacy options are enabled.
Which is normal.
I looked in the console at this page on desktop, which uses an external javascript script (see screenshot)
I think the person has an extension or configuration that blocks trackers


![issue28](https://user-images.githubusercontent.com/182199/46069472-e57b4780-c17b-11e8-8603-620953ca6f19.png)
